# Generated by Django 5.2.15 on 2026-07-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_spam",
            field=models.BooleanField(default=False),
        ),
    ]
